from django.db import models

# Create your models here.
class FugitiveProfiles(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    alias = models.CharField(max_length=200)
    height = models.CharField(max_length=200)
    weight = models.CharField(max_length=200)
    eyes = models.CharField(max_length=200)
    hair = models.CharField(max_length=200)
    distinguishing_marks = models.CharField(max_length=200)
    nationality = models.CharField(max_length=200)
    date_of_birth = models.CharField(max_length=200)
    place_of_birth = models.CharField(max_length=200)
    charges = models.CharField(max_length=200)
    wanted_by = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    publication = models.CharField(max_length=200)
    last_modified = models.DateField()
    reward = models.CharField(max_length=200)
    details = models.TextField(max_length=200)
    caution = models.TextField(max_length=200)
    remarks = models.TextField(max_length=200)
    images = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
