# Generated by Django 4.2.5 on 2023-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FugitiveProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('height_in_cm', models.IntegerField()),
                ('weight_in_kg', models.IntegerField()),
                ('eyes', models.CharField(max_length=255)),
                ('hair', models.CharField(max_length=255)),
                ('distinguishing_marks', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('charges', models.CharField(max_length=255)),
                ('wanted_by', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('publication', models.CharField(max_length=255)),
                ('last_modified', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=255)),
                ('caution', models.TextField(max_length=255)),
                ('remarks', models.TextField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
