# Generated by Django 4.2.5 on 2023-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnifiedFugitiveDatabase', '0003_alter_fugitiveprofiles_distinguishing_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fugitiveprofiles',
            name='alias',
            field=models.TextField(),
        ),
    ]
